"""initial_phase1_schema

Revision ID: 8b85071c8e5c
Revises: 
Create Date: 2026-09-05 18:42:36.969969
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8b85071c8e5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_ingestion_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_code', sa.String(length=64), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_written', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_ingestion_runs'))
    )
    op.create_index('ix_data_ingestion_runs_status_completed', 'data_ingestion_runs', ['status', 'completed_at'], unique=False)
    op.create_table('indices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indices')),
    sa.UniqueConstraint('provider', 'symbol', name='uq_indices_provider_symbol')
    )
    op.create_index(op.f('ix_indices_symbol'), 'indices', ['symbol'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('trading_symbol', sa.String(length=64), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('security_type', sa.String(length=32), nullable=False),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('delisting_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_securities')),
    sa.UniqueConstraint('exchange', 'symbol', name='uq_securities_exchange_symbol'),
    sa.UniqueConstraint('isin', name=op.f('uq_securities_isin'))
    )
    op.create_index('ix_securities_active_exchange', 'securities', ['is_active', 'exchange'], unique=False)
    op.create_index('ix_securities_symbol', 'securities', ['symbol'], unique=False)
    op.create_table('strategy_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('strategy_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_definitions')),
    sa.UniqueConstraint('strategy_code', 'version', name='uq_strategy_definitions_code_version')
    )
    op.create_table('trading_calendar',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('is_trading_day', sa.Boolean(), nullable=False),
    sa.Column('session_open', sa.Time(), nullable=True),
    sa.Column('session_close', sa.Time(), nullable=True),
    sa.Column('session_type', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trading_calendar')),
    sa.UniqueConstraint('exchange', 'trading_date', name='uq_trading_calendar_exchange_date')
    )
    op.create_index('ix_trading_calendar_lookup', 'trading_calendar', ['exchange', 'is_trading_day', 'trading_date'], unique=False)
    op.create_table('corporate_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('announcement_date', sa.Date(), nullable=True),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('ratio_numerator', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('ratio_denominator', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('cash_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('ratio_denominator IS NULL OR ratio_denominator > 0', name=op.f('ck_corporate_actions_positive_ratio_denominator')),
    sa.CheckConstraint('ratio_numerator IS NULL OR ratio_numerator > 0', name=op.f('ck_corporate_actions_positive_ratio_numerator')),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_corporate_actions_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corporate_actions'))
    )
    op.create_index('ix_corporate_actions_security_ex_date', 'corporate_actions', ['security_id', 'ex_date'], unique=False)
    op.create_table('daily_prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('traded_value', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('close >= low AND close <= high', name=op.f('ck_daily_prices_close_within_range')),
    sa.CheckConstraint('high >= low', name=op.f('ck_daily_prices_high_gte_low')),
    sa.CheckConstraint('open >= 0 AND high >= 0 AND low >= 0 AND close >= 0', name=op.f('ck_daily_prices_nonnegative_prices')),
    sa.CheckConstraint('open >= low AND open <= high', name=op.f('ck_daily_prices_open_within_range')),
    sa.CheckConstraint('volume >= 0', name=op.f('ck_daily_prices_nonnegative_volume')),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_daily_prices_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_prices')),
    sa.UniqueConstraint('security_id', 'trading_date', name='uq_daily_prices_security_date')
    )
    op.create_index('ix_daily_prices_security_date', 'daily_prices', ['security_id', 'trading_date'], unique=False)
    op.create_index('ix_daily_prices_trading_date', 'daily_prices', ['trading_date'], unique=False)
    op.create_table('fundamental_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('fiscal_period_start', sa.Date(), nullable=False),
    sa.Column('fiscal_period_end', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('reported_date', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False, comment='First date this version was publicly knowable'),
    sa.Column('revenue', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('operating_profit', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('net_profit', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('eps', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('cash', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('equity', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('fiscal_period_end >= fiscal_period_start', name=op.f('ck_fundamental_reports_valid_fiscal_period')),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_fundamental_reports_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fundamental_reports')),
    sa.UniqueConstraint('security_id', 'fiscal_period_end', 'reported_date', 'source', name='uq_fundamentals_report_version')
    )
    op.create_index('ix_fundamentals_point_in_time', 'fundamental_reports', ['security_id', 'effective_date', 'fiscal_period_end'], unique=False)
    op.create_table('index_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('index_id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name=op.f('ck_index_memberships_valid_membership_range')),
    sa.ForeignKeyConstraint(['index_id'], ['indices.id'], name=op.f('fk_index_memberships_index_id_indices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_index_memberships_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_index_memberships')),
    sa.UniqueConstraint('index_id', 'security_id', 'valid_from', name='uq_index_memberships_interval')
    )
    op.create_index('ix_index_memberships_as_of', 'index_memberships', ['index_id', 'valid_from', 'valid_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_index_memberships_as_of', table_name='index_memberships')
    op.drop_table('index_memberships')
    op.drop_index('ix_fundamentals_point_in_time', table_name='fundamental_reports')
    op.drop_table('fundamental_reports')
    op.drop_index('ix_daily_prices_trading_date', table_name='daily_prices')
    op.drop_index('ix_daily_prices_security_date', table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_index('ix_corporate_actions_security_ex_date', table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index('ix_trading_calendar_lookup', table_name='trading_calendar')
    op.drop_table('trading_calendar')
    op.drop_table('strategy_definitions')
    op.drop_index('ix_securities_symbol', table_name='securities')
    op.drop_index('ix_securities_active_exchange', table_name='securities')
    op.drop_table('securities')
    op.drop_index(op.f('ix_indices_symbol'), table_name='indices')
    op.drop_table('indices')
    op.drop_index('ix_data_ingestion_runs_status_completed', table_name='data_ingestion_runs')
    op.drop_table('data_ingestion_runs')
    # ### end Alembic commands ###
